version: '3'
services:
    sqlserver:
        image: 'microsoft/mssql-server-linux:latest'
        container_name: sqlserver
        volumes:
            - 'sqlserverdata:/var/opt/mssql'
        ports:
            - '1434:1433'
        environment:
            ACCEPT_EULA: Y
            MSSQL_PID: Developer
            SA_PASSWORD: 8jkGh47hnDw89Haq8LN2
    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: rabbitmq
        volumes:
            - 'rabbitmqdata:/var/lib/rabbitmq'
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmquser
            RABBITMQ_DEFAULT_PASS: DEBmbwkSrzy9D1T9cJfa

    # customermanagementapi:
        # image: pitstop/customermanagementapi:latest
        # build:
          # context: ./
          # dockerfile: Dockerfile.customermanagement
        # container_name: customermanagementapi
        # depends_on:
          # - rabbitmq
          # - sqlserver
        # ports:
          # - "5100:5100"
        # environment:
          # - ASPNETCORE_ENVIRONMENT=Production
          # - ApplicationInsights:InstrumentationKey=${PitStopAIKey}

    # logisticsmanagementapi:
        # image: 'pitstop/logisticsmanagementapi:latest'
        # build: 
            # context: ./
            # dockerfile: Dockerfile.logistics
        # container_name: logisticsmanagementapi
        # depends_on:
            # - rabbitmq
            # - sqlserver
        # ports:
            # - '5300:5300'
        # environment:
            # ASPNETCORE_ENVIRONMENT: Production
            # ApplicationInsights: 'InstrumentationKey=$${PitStopAIKey}'
            
    # orderapi:
        # image: 'pitstop/orderapi:latest'
        # build: 
            # context: ./
            # dockerfile: Dockerfile.orders
        # container_name: orderapi
        # depends_on:
            # - rabbitmq
            # - sqlserver
        # ports:
            # - '5600:5600'
        # environment:
            # ASPNETCORE_ENVIRONMENT: Production
            # ApplicationInsights: 'InstrumentationKey=$${PitStopAIKey}'

    # productmanagementapi:
        # image: pitstop/productmanagementapi:latest
        # build:
            # context: ./
            # dockerfile: Dockerfile.product
        # container_name: productmanagementapi
        # depends_on:
           # - rabbitmq
           # - sqlserver
        # ports:
           # - "5500:5500"
        # environment:
           # - ASPNETCORE_ENVIRONMENT=Production
    # shippingservice:
        # image: 'pitstop/shippingservice:latest'
        # build:
            # context: ./
            # dockerfile: Dockerfile.shipping
        # container_name: shippingservice
        # depends_on:
            # - rabbitmq
            # - sqlserver
        # environment:
            # ASPNETCORE_ENVIRONMENT: Production
    # auditlogservice:
    #     image: 'pitstop/auditlogservice:latest'
    #     build: AuditlogService
    #     container_name: auditlogservice
    #     depends_on:
    #         - rabbitmq
    #     environment:
    #         PITSTOP_ENVIRONMENT: Production
    # invoiceservice:
    #     image: 'pitstop/invoiceservice:latest'
    #     build: InvoiceService
    #     container_name: invoiceservice
    #     depends_on:
    #         - rabbitmq
    #         - sqlserver
    #     environment:
    #         PITSTOP_ENVIRONMENT: Production
    # notificationservice:
    #     image: 'pitstop/notificationservice:latest'
    #     build: NotificationService
    #     container_name: notificationservice
    #     depends_on:
    #         - rabbitmq
    #         - sqlserver
    #         - mailserver
    #     environment:
    #         PITSTOP_ENVIRONMENT: Production
    timeservice:
        image: 'pitstop/timeservice:latest'
        build:
            context: ./
            dockerfile: Dockerfile.time
        container_name: timeservice
        depends_on:
            - rabbitmq
        environment:
            PITSTOP_ENVIRONMENT: Production

volumes:
    sqlserverdata:
        external: true
    rabbitmqdata:
        external: true
