FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy everything else and build
COPY . ./
RUN dotnet restore PaymentAPI/*.csproj
RUN dotnet publish PaymentAPI/*.csproj -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
COPY --from=build-env /app/PaymentAPI/out .

# Expose ports
EXPOSE 6000/tcp
ENV ASPNETCORE_URLS http://*:5900

# Configure environment variables
ENV WEBSITE_SITE_NAME OrderAPI

# Start
ENTRYPOINT ["dotnet", "PaymentAPI.dll"]